# Generated by Django 2.1.5 on 2019-02-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puresite',
            name='site_ptr',
        ),
        migrations.AddField(
            model_name='puresite',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Site'),
        ),
    ]
