# Generated by Django 2.1.5 on 2019-02-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190217_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puresite',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Site'),
        ),
    ]
