# Generated by Django 2.1.5 on 2019-03-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190317_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='elements',
        ),
        migrations.AddField(
            model_name='element',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Page'),
            preserve_default=False,
        ),
    ]
