# Generated by Django 2.1.5 on 2019-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190319_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='href',
            field=models.CharField(default='index.html', max_length=200),
        ),
    ]
