# Generated by Django 2.1.5 on 2019-03-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_page_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='atributeValues',
            new_name='attributeValues',
        ),
    ]
